# NOTE: RISK_MODEL is only valid when INTERVENTION = "Tracing"
RISK_MODEL : "digital" # "naive"  "manual", "digital", "transformer"
SHOULD_MODIFY_BEHAVIOR : True

## INTERVENTIONS
INTERVENTION : "Tracing"

TRACING_ORDER : 2
REC_LEVEL_THRESHOLDS: [0, 0, 1] # Binary

N_BEHAVIOR_LEVELS: 4

