# EXPERIMENTAL PARAMETERS
COLLECT_LOGS: True
COLLECT_TRAINING_DATA: False
USE_INFERENCE_SERVER: False
RISK_MODEL: "transformer" # "naive"  "manual", "digital", "transformer"
SHOULD_MODIFY_BEHAVIOR: True
USE_ORACLE: True
ORACLE_NOISE: 0.0

## INTERVENTIONS
INTERVENTION: "Tracing"

# TWILIGHT-RAIN-696
TRANSFORMER_EXP_PATH: "https://drive.google.com/file/d/1kXA-0juviQOL0R08YlQpaS5gKumQ8zrT"
CLUSTER_PATH: "output/clusters"

RISK_MAPPING:
  [
    0.0,
    0.010190361,
    0.022800818,
    0.033924844,
    0.044960417,
    0.0564146,
    0.069076724,
    0.08331901,
    0.09839013,
    0.115344636,
    0.13295256,
    0.15386948,
    0.1748018,
    0.19909734,
    0.22582635,
    0.26276696,
    1.0,
  ]
