---
# EXPERIMENTAL PARAMETERS
COLLECT_LOGS : True
COLLECT_TRAINING_DATA : True
USE_INFERENCE_SERVER : True
RISK_MODEL : "naive" # "naive"  "manual", "digital", "transformer"
INIT_PERCENT_SICK : 0.0025
SHOULD_MODIFY_BEHAVIOR : True
USE_ORACLE: False

## INTERVENTIONS
INTERVENTION_DAY : -1
INTERVENTION : "Tracing"
PERCENT_FOLLOW : 1.0
P_HAS_APP : 1.0
ABSOLUTE_P_HAS_APP : True # If False, we modulate P_HAS_APP with carefulness and age


# PATHS
CLUSTER_PATH : "output/clusters"

# Inference & Training
INFECTIOUSNESS_N_DAYS_HISTORY : 14
TRACING_N_DAYS_HISTORY : 14
MP_BATCHSIZE : "auto"
MP_N_JOBS : "1"
MP_BACKEND : "loky"
DUMP_CLUSTERS : True
CLUSTER_TYPE : "heuristic" # "random", "graph"


# TRACING RISK MODEL PARAMETERS  (non-ML)
TRACE_SYMPTOMS : True
TRACE_RISK_UPDATE : False
TRACING_ORDER : 1
UPDATES_PER_DAY : 4
RISK_MAPPING : [0., 0.01, 0.20009698, 0.3337032 , 0.42782824,
                0.53769504, 0.62646553, 0.72454666, 0.79687407, 0.8408014,
                0.87897228, 0.90514533, 0.92788853, 0.94996601, 0.97018845,
                0.98973414, 1.]
