#FORMER COMMAND-LINE ARGS
COVID_START_DAY: 7
n_people: 1000
init_fraction_sick: 0.001
start_time:
  "2020-02-28 00:00:00" # in utils.py/parse_configuration, this will be parsed
  # into a datetime object with the following schema: '%Y-%m-%d %H:%M:%S'
simulation_days: 30
outdir: ./output
out_chunk_size: null
seed: 0
tune: False
print_progress: True
zip_outdir: False
delete_outdir: False

# EXPERIMENTAL PARAMETERS
COLLECT_LOGS: False
COLLECT_TRAINING_DATA: False
USE_INFERENCE_SERVER: False
RISK_MODEL: "" # "naive"  "manual", "digital", "transformer"
SHOULD_MODIFY_BEHAVIOR: True
USE_ORACLE: False
INFERENCE_SERVER_ADDRESS: null

## INTERVENTIONS
N_BEHAVIOR_LEVELS: 2
INTERVENTION: ""
INTERVENTION_DAY: -1
# NOTE: INTERVENTION is only valid if INTERVENTION_DAY >= 0
DROPOUT_RATE: 0.02
# NOTE: HAS_APP params are only used when an app based INTERVENTION = "Tracing" is used
APP_UPTAKE: -1.0

REC_LEVEL_THRESHOLDS: [1, 3, 5] # how to convert risk_levels to rec_levels
MAX_RISK_LEVEL: 15 # maximum allowed risk_level => assert risk_level in range(0, MAX_RISK_LEVEL + 1)

# Inference & Training
TRACING_N_DAYS_HISTORY: 14
DUMP_CLUSTERS: False
CLUSTER_ALGO_TYPE: "blind" # should be in ["old", "blind", "naive", "perfect", "simple"]

UPDATES_PER_DAY: 4
TRACE_SYMPTOMS : False
TRACE_RISK_UPDATE : False
TRACING_ORDER: 1
# by default, we use a roughly linear interpolation to map the risk values
RISK_MAPPING: [
  0.    , 0.0625, 0.125 , 0.1875, 0.25  , 0.3125, 0.375 , 0.4375,
  0.5   , 0.5625, 0.625 , 0.6875, 0.75  , 0.8125, 0.875 , 0.9375,
  1.    , 1.0625,
]
